// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'pref-help'
  | 'pref-secondary-ascending'
  | 'pref-sort-on-first-render'
  | 'pref-title'
  | 'prefs-title'
  | 'tag-column';
